# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20151223_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skillset1',
            new_name='skillset',
        ),
    ]
