# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 08:13
from __future__ import unicode_literals

import details.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20151223_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=details.models.get_upload_file_name),
        ),
    ]
